---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: myvol
  namespace: quota
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/data
    server: 192.168.1.10
    readOnly: false
